namespace GFDLibrary.Animations
{
    public enum KeyType
    {
        Invalid,
        NodePR,
        NodePRS,
        Vector3,
        Quaternion,
        Single,
        Vector3_2 = 6,
        EKeyType_AmbientColor = 6,
        Vector3_3 = 7,
        EKeyType_DiffuseColor = 7,
        Vector3_4 = 8,
        EKeyType_SpecularColor = 8,
        Single_2,
        Quaternion_2,
        Single_3,
        MaterialSingle_4 = 12,
        EKeyType_Opacity = 12,
        Single5 = 13,
        EKeyType_UV0Transform = 13,
        MaterialVector3_5 = 14,
        EKeyType_EmissiveColor = 14,
        Single_5,
        Single_6,
        NodePRSByte,
        Single4Byte = 18,
        EKeyType_MeshColor = 18,
        SingleByte,
        Single5_2 = 20,
        EKeyType_UV1Transform = 20,
        Single5Alt = 21,
        EKeyType_UV0Transform_NoInterp = 21,
        Type22,
        CameraFieldOfView,
        Single_8,
        SingleAlt_2,
        NodePRHalf,
        NodePRSHalf,
        NodePRHalf_2,
        MaterialSingle_9,
        SingleAlt_3,
        Type31,
        NodeRHalf,
        NodeSHalf,
        NodePSHalf,
        NodeRSHalf,
        Type36_P5R = 36,
        EKeyType_UV1Transform_NoInterp = 36
    }
}